# Generated by Django 3.0.8 on 2020-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometer',
            name='serial_id',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
