version: '3.7'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn nixnox.wsgi:application --bind 0.0.0.0:8000  
        env_file:
        - ./.env.prod
        volumes:
        - .:/nixnox_project
        expose:
        - 8000
        ports:
        - 8888:8888
        depends_on:
        - db
        - redis
        links:
        - redis
    db:
        image: postgis/postgis:12-2.5
        volumes:
        - postgres_data:/var/lib/postgresql/data/

    redis:
        image: "redis:alpine"
        ports:
        - "6379:6379"
        depends_on:
          - db

    celery:
        build: .
        command: celery -A nixnox worker -l info
        volumes:
            - .:/nixnox_project
        depends_on:
            - web
            - db
            - redis
            - nginx
        env_file:
            - ./.env.prod
        links:
            - redis
            - db
    celery-beat:
        build: .
        command: celery -A nixnox beat -l info
        volumes:
            - .:/nixnox_project
        depends_on:
            - web
            - db
            - redis
            - nginx
        env_file:
            - ./.env.prod
        links:
            - redis
            - db
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web
        volumes:
            - .:/nixnox_project
        links:
            - redis

volumes:
    postgres_data:
