# Generated by Django 3.0.8 on 2020-08-07 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allskymaps', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='photometer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Photometer'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allskymaps.Observation'),
        ),
    ]
