# Generated by Django 3.0.8 on 2020-08-07 08:45

import allskymaps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allskymaps', '0002_auto_20200807_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='place',
            field=models.CharField(default='Somewhere', help_text='Place where measurements were taken.', max_length=250),
        ),
        migrations.AddField(
            model_name='observation',
            name='region',
            field=models.CharField(default='Noplace', max_length=250),
        ),
        migrations.AlterField(
            model_name='observation',
            name='comments',
            field=models.TextField(default='No comments on this site', help_text="Any comments on this site e. g. 'there were clous', 'easy acces' or anything remarkable.", max_length=2000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='humidity',
            field=models.DecimalField(decimal_places=3, default=99.0, help_text='Air humidity. If no value were recorded during measurements, pleas leave it as it is.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='observation',
            name='measurements_file',
            field=models.FileField(help_text="forms .txt file with measurements. Be sure this file was not edited after it's creation by the app", upload_to=allskymaps.models.user_directory_path_measurements),
        ),
    ]
