# Generated by Django 3.0.8 on 2020-08-07 12:03

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allskymaps', '0003_auto_20200807_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='gispoint',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
