# Generated by Django 3.0.8 on 2020-08-08 16:49

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_institution'),
        ('allskymaps', '0005_worldborder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='time',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='observation',
            name='institution',
            field=models.ForeignKey(default='24f2bd47-c66a-4633-9234-d4b9108b98ae', on_delete=django.db.models.deletion.PROTECT, to='users.Institution'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='observation',
            name='gispoint',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
