# Generated by Django 3.1 on 2020-08-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allskymaps', '0007_auto_20200809_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='altitude',
            new_name='elevation',
        ),
    ]
