# Generated by Django 3.1 on 2020-09-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allskymaps', '0008_auto_20200809_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='KocijafBara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.DecimalField(decimal_places=2, max_digits=3)),
                ('t', models.DecimalField(decimal_places=2, max_digits=3)),
                ('s1', models.DecimalField(decimal_places=5, max_digits=6)),
                ('s2', models.DecimalField(decimal_places=5, max_digits=6)),
                ('s3', models.DecimalField(decimal_places=5, max_digits=6)),
                ('s4', models.DecimalField(decimal_places=5, max_digits=6)),
                ('l1', models.DecimalField(decimal_places=5, max_digits=7)),
                ('l2', models.DecimalField(decimal_places=5, max_digits=7)),
                ('l3', models.DecimalField(decimal_places=5, max_digits=7)),
                ('l4', models.DecimalField(decimal_places=5, max_digits=7)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allskymaps.observation')),
            ],
        ),
    ]
