# Generated by Django 3.1 on 2020-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allskymaps', '0009_kocijafbara'),
    ]

    operations = [
        migrations.AddField(
            model_name='kocijafbara',
            name='time_spent',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=5),
        ),
    ]
